logging:
    level:
        com:
            abcshopping: DEBUG
spring:
     sleuth:
    	sampler:
	     probability: 1.0	
    jpa:
        show-sql: true
        generate-ddl: true
    zipkin:
        base-url: http://localhost:9411/
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.MySQL55Dialect
    datasource:
        initialization-mode: always
        # url: jdbc:mysql://us-cdbr-iron-east-01.cleardb.net/ad_a3d2e1b1b1e2220?user=b3a251b1221761&password=c90ab886
        # driver: com.mysql.jdbc.Driver
