logging:
    level:
        com:
            abcshopping: DEBUG
spring:
    jpa:
        show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    datasource:
        initialization-mode: always
    
