logging:
    level:
        io:
            pivotal: DEBUG
security:
     basic:
      enabled: false
management:
    security:
        enabled: false
greeting:
    displayFortune: false
quoteServiceURL: https://quote-service-dev.cfapps.io/quote
