logging:
    level:
        io:
            pivotal: DEBUG

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

server:
  port: 8083
